---
  redis-url: "localhost"
  redis-port: 6379
  redis-password: ""

  cowrie-key: ""

  influx-address: ""
  influx-token: ""
  influx-organization: ""
  influx-bucket: ""
  influx-measurement: ""

  ipinfo-key: ""